#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 plasma-deepin-theme contributors
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the Deepin Light / Deepin Dark KDE color schemes.

Base values are taken from DTK (linuxdeepin/dtkgui,
src/kernel/dguiapplicationhelper.cpp: light_qpalette, dark_qpalette,
light_dpalette, dark_dpalette). DTK uses semi-transparent text colors;
KDE color schemes need opaque colors, so text colors are pre-blended
onto the window background. Values marked "own" are not from DTK.
"""
import os
import sys


def hx(c):
    c = c.lstrip('#')
    return tuple(int(c[i:i + 2], 16) for i in (0, 2, 4))


def blend(fg, alpha, bg):
    fg, bg = hx(fg), hx(bg)
    return '#%02x%02x%02x' % tuple(round(alpha * f + (1 - alpha) * b) for f, b in zip(fg, bg))


def rgb(c):
    return ','.join(str(v) for v in hx(c))


LIGHT = dict(
    name='Deepin Light', id='DeepinLight',
    window='#f8f8f8',                      # DTK Window
    window_alt='#efefef',                  # own
    view='#ffffff',                        # DTK Base
    view_alt=blend('#000000', 0.03, '#ffffff'),  # DTK AlternateBase (3% black)
    button='#e5e5e5',                      # DTK Button
    button_alt='#d9ecff',                  # own (tinted accent)
    header='#f8f8f8',                      # = window: title bar, tool bars and content form one glass surface
    header_inactive='#f8f8f8',
    text=blend('#000000', 0.85, '#f8f8f8'),      # DTK TextTitle 85% black
    text_inactive=blend('#000000', 0.6, '#f8f8f8'),  # DTK TextTips 60% black
    accent='#0081ff',                      # DTK Highlight / LightLively
    accent_text='#ffffff',                 # DTK HighlightedText
    link='#0082fa',                        # DTK Link
    visited='#ad4579',                     # DTK LinkVisited
    negative='#ff5736',                    # DTK TextWarning
    neutral='#ff9b00',                     # own
    positive='#00a650',                    # own
    tooltip='#ffffff',                     # DTK ToolTipBase (80% white, opaque here)
    tooltip_text=blend('#000000', 0.85, '#ffffff'),
    compl='#2a2a2a', compl_alt='#202020', compl_text='#f0f0f0', compl_inactive='#a8a8a8',
)

DARK = dict(
    name='Deepin Dark', id='DeepinDark',
    window='#252525',                      # DTK Window (dark)
    window_alt='#2c2c2c',                  # own
    view='#282828',                        # DTK Base (dark)
    view_alt=blend('#ffffff', 0.05, '#282828'),  # own (5% white)
    button='#444444',                      # DTK Button (dark)
    button_alt='#17345a',                  # own
    header='#252525',                      # = window, see above
    header_inactive='#252525',
    text=blend('#ffffff', 0.85, '#252525'),      # DTK TextTitle 85% white
    text_inactive=blend('#ffffff', 0.6, '#252525'),  # DTK TextTips 60% white
    accent='#0059d2',                      # DTK LightLively/DarkLively (dark)
    accent_text='#f1f6ff',                 # DTK HighlightedText (dark)
    link='#0082fa',                        # DTK Link
    visited='#ad4579',                     # DTK LinkVisited
    negative='#e43f2e',                    # DTK TextWarning (dark)
    neutral='#e88b00',                     # own
    positive='#1fb86a',                    # own
    tooltip='#2d2d2d',                     # DTK ToolTipBase (dark, opaque here)
    tooltip_text=blend('#ffffff', 0.85, '#2d2d2d'),
    compl='#1b1b1b', compl_alt='#141414', compl_text='#f0f0f0', compl_inactive='#a0a0a0',
)


def section(name, bg, bg_alt, fg, fg_inactive, p, active=None, fg_active=None):
    fg_active = fg_active or p['accent']
    return f"""[Colors:{name}]
BackgroundAlternate={rgb(bg_alt)}
BackgroundNormal={rgb(bg)}
DecorationFocus={rgb(p['accent'])}
DecorationHover={rgb(p['accent'])}
ForegroundActive={rgb(fg_active)}
ForegroundInactive={rgb(fg_inactive)}
ForegroundLink={rgb(p['link'])}
ForegroundNegative={rgb(p['negative'])}
ForegroundNeutral={rgb(p['neutral'])}
ForegroundNormal={rgb(fg)}
ForegroundPositive={rgb(p['positive'])}
ForegroundVisited={rgb(p['visited'])}

"""


def scheme(p):
    out = """# SPDX-FileCopyrightText: 2026 plasma-deepin-theme contributors
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by tools/gen-colors.py - edit the generator, not this file.

[ColorEffects:Disabled]
Color=56,56,56
ColorAmount=0
ColorEffect=0
ContrastAmount=0.55
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color=112,111,110
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

"""
    out += section('Button', p['button'], p['button_alt'], p['text'], p['text_inactive'], p)
    out += section('Complementary', p['compl'], p['compl_alt'], p['compl_text'], p['compl_inactive'], p)
    out += section('Header', p['header'], p['window'], p['text'], p['text_inactive'], p)
    out += section('Header][Inactive', p['header_inactive'], p['window'], p['text'], p['text_inactive'], p)
    out += section('Selection', p['accent'], p['button_alt'], p['accent_text'], p['accent_text'], p,
                   fg_active=p['accent_text'])
    out += section('Tooltip', p['tooltip'], p['window'], p['tooltip_text'], p['text_inactive'], p)
    out += section('View', p['view'], p['view_alt'], p['text'], p['text_inactive'], p)
    out += section('Window', p['window'], p['window_alt'], p['text'], p['text_inactive'], p)
    out += f"""[General]
ColorScheme={p['id']}
Name={p['name']}
Name[de]={p['name'].replace('Light', 'Hell').replace('Dark', 'Dunkel')}
shadeSortColumn=true

[KDE]
contrast=4

[WM]
activeBackground={rgb(p['header'])}
activeBlend={rgb(p['header'])}
activeForeground={rgb(p['text'])}
inactiveBackground={rgb(p['header_inactive'])}
inactiveBlend={rgb(p['header_inactive'])}
inactiveForeground={rgb(p['text_inactive'])}
"""
    return out


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '..', 'color-schemes')
    os.makedirs(outdir, exist_ok=True)
    for p in (LIGHT, DARK):
        with open(os.path.join(outdir, p['id'] + '.colors'), 'w') as f:
            f.write(scheme(p))
        print('wrote', p['id'] + '.colors')


if __name__ == '__main__':
    main()
